package(default_visibility = ["//visibility:public"])

java_binary(
    name = "osgi_bundle_builder",
    runtime_deps = ["//third_party:osgi_bundle_builder_artifact"],
    main_class = "com.liferay.osgi.bundle.builder.OSGiBundleBuilder"
)